export const world = `
....................
a....o.....o...o....
--...-.....-...--...
....................
......c...k...k....c
...=..-...=...=...--
.................-..
....................
.....-..=....#......
....................
.........#..........
...............=....
............-.......
........e..=..o.....
........===...=.....
....................
`;

export const solution = '{"blocks":{"languageVersion":0,"blocks":[{"type":"events_bush","id":"@wUlKId(*46%1goV(ehs","x":96,"y":75,"next":{"block":{"type":"actions_jump","id":"lIWLv}!3sW^mr!S^{Ope","fields":{"TYPE":"high"}}}},{"type":"events_edge","id":"0qU0LagT6h.qaZMcOWX?","x":243,"y":82,"next":{"block":{"type":"controls_if","id":"u=?pjl_hbJx|Vz@dy9O.","inputs":{"IF0":{"block":{"type":"conditions_ground","id":"y4]J825b+p-M)??nMtA+","fields":{"TYPE":"grass"}}},"DO0":{"block":{"type":"actions_jump","id":"DGq8emFSs}j(UPZ_8?#8","fields":{"TYPE":"high"}}}}}}},{"type":"events_cactus","id":"d6[t7wQ.4hSn(7:u#tNs","x":95,"y":172,"next":{"block":{"type":"actions_turn","id":"9AoiYF|b{wb?Me,/z3s%"}}}]}}';