export const world = `
....................
a......c............
===...==...==....###
....................
..........c....ok...
=...o.#...==...==...
...===..............
....................
.k..................
.==.....c...........
.......==.....k.....
.............##.....
..........co........
..........===.......
..e.................
..===...............
`;

export const solution = '{"blocks":{"languageVersion":0,"blocks":[{"type":"events_cactus","id":"(N2HVv.X^ls714GCu7gV","x":8,"y":55,"next":{"block":{"type":"actions_jump","id":"w|,F=R3jPfTCZh|d:A^F","fields":{"TYPE":"long"}}}},{"type":"events_edge","id":"-uP/,.2[gQkrz,Eq1B7i","x":146,"y":56,"next":{"block":{"type":"controls_if","id":"U_TiHJpSzz62fDWu[!`O","inputs":{"IF0":{"block":{"type":"conditions_ground","id":":E1w]?rY#*cM|3s72C$n","fields":{"TYPE":"grass"}}},"DO0":{"block":{"type":"actions_jump","id":"[*@cM(+?*QJCwNe=}o(U","fields":{"TYPE":"long"}}}}}}},{"type":"events_bush","id":"!nTF^RRhD^nRw)ZI6zmG","x":47,"y":193,"next":{"block":{"type":"actions_turn","id":"bEq0@Y(=I$pOOgXtK/]}"}}}]}}';